CREATE TABLE events (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    place varchar(100) NOT NULL
);

CREATE TABLE teams (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    surname varchar(100) NOT NULL,
    event_id int REFERENCES events(id) ON DELETE SET NULL
);

CREATE TABLE teams (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    surname varchar(100) NOT NULL,
    age int,
    team_id int REFERENCES teams(id) ON DELETE SET NULL
);

-- очистка данных таблицы
TRUNCATE Table person;

-- добавление столбца в таблицу
ALTER TABLE Person Add COLUMN role varchar(100) not null;
